version: '3'
networks: 
  cdr-radicacion-network:
    external: true

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: c@m@r@secr3t4
    volumes:
      - /opt/mysql:/var/lib/mysql
    networks:
      - cdr-radicacion-network
        
  phpmyadmin:
    depends_on:
            - db
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db     
      PMA_USER: root 
      PMA_PASSWORD: c@m@r@secr3t4
    networks:
      - cdr-radicacion-network  

  tl-server:
    image: tl-server
    ports:
      - "9000:9000"
    networks:
      - cdr-radicacion-network
    volumes: 
      - ./:/app/
    depends_on:
      - db     
    environment:
      DB_HOSTNAME: db
      MYSQL_ROOT_PASSWORD: c@m@r@secr3t4